spring:
  profiles:
    default: local

server:
  port: 8080

springdoc:
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    operations-sorter: alpha # alpha(알파벳 오름차순), method(HTTP메소드순)
    tags-sorter: alpha # 태그 정렬 기준
    path: /swagger-ui # html 문서 접속 경로
  paths-to-match:
    - /**
  cache:
    disabled: true